### ISSUE TITLE
Additional locale CI Jobs / Scripts

### ISSUE THREAD

**Issue by rossbulat** [paritytech/polkadot-staking-dashboard#445]
This issue is for tracking the CI support of managing locales.

### New CI Jobs:
- [x] `yarn locale:validate`
   - [x] Check keys match: #434 
   - [x] Check if keys are ordered alphabetically: #513 

### New Scripts:
- [x] `yarn locale:order`. Automatically order keys in every file: #508
